### ISSUE TITLE
arenas.yml params override section.

### ISSUE THREAD

**Issue by Europia79** [BattlePlugins/BattleArena#1]
arenas.yml has a section called params: which is supposed to override values from {ArenaType}Config.yml.

However, doCommands values are not working for this section.

And adambor reported that the Scoreboard is not displaying the correct number of players: it was displaying the value from FutbolConfig.yml, not the overriden value from arenas.yml params section.

**Comment by lDucks** [comment]
Is this resolved? It's been 8 months.

**Comment by Europia79** [comment]
> Is this resolved? It's been 8 months.

No, i haven't fixed this issue yet. Luckily, it doesn't seem to be that big of an issue, because not many players are reporting problems here. Using the parent values will be how the major of servers will configure their arena.

I suspect overriding the parent values in order to further customize individual arenas is a rare use-case scenario for server admins.

**Comment by graywolf336** [comment]
Going to comment on this and say I just ran into this bug and was getting frustrated as I couldn't figure out what I was doing wrong...
