### ISSUE TITLE
Reload Is broken for all competitions.

### ISSUE THREAD

**Issue by TKwSni** [BattlePlugins/BattleArena#103]
Spigot: 1.13.2
BattleArena: 3.9.11.0

/battlearena reload doesnt reload all the configs correctly

Edited ArenaConfig.yml:
- /ba reload, /battlearena reload did not work.
- /arena reload Only reloaded parts of the config.yml like the prefix, and some options, but not all of them, players were joining with an empty inventory.

After a complete server restart, everything was good.

**Comment by Zach443** [comment]
Will look into this in the next few days.

**Comment by RednedEpic** [comment]
Specifically, what was not loading correctly? I was working with BattleArena yesterday and everything appeared to reload correctly after running both /battlearena reload and /arena reload.

**Comment by supawiz6991** [comment]
I've reproduced this in the latest version. 
/ba reload is not reloading classes.yml nor the competitions.yml files reliably. I've found that I end up having to do a server restart to get it to reload the configs.
Those are the only two I've noticed thus far.
