### ISSUE TITLE
Heroes Compatibility Problems (With PR Link to fix them)

### ISSUE THREAD

**Issue by Delfofthebla** [BattlePlugins/BattleArena#105]
======== Problem 1 =========

BattleArena displays the winner's decimal value health with no formatting. This results in a very long number for any plugin that modifies health or damage numbers to decimal values.

Solution: BA should format the decimal value to 1 or 2 decimal places.

======== Problem 2 =========

Heroes has damage listeners that will sometimes cancel a damage event against a target that is inside of an arena (Such as invulnerability skills, or if the attacker is in a "stunned" state). BattleArena will _un-cancel_ these events and thus cause compatibility problems with Heroes.

Solution: BA should defer to Heroes to handle this themselves.

======== Problem 3 =========

BattleArena will store the user's class on entry to an arena, and set their class back to normal after they leave. I assume this has to do with the signs and allowing arenas to put players into a temporary class while inside without costing the player any money to switch classes in Heroes.

This is fine, but the problem is that it seems to only store the class once and then never again. So if a player switches classes after leaving the arena, it will put them in the previously stored class the next time they queue for an arena.

Solution: BA should store their class every time the player queues.

======== Problem 4 =========

BattleArena does not clear summons after ending an arena. This can leave mobs just hanging around on the inside that interfere with future fights in the same arena.

Solution: BA should use the Heroes API method to clear a player's summons on entry / exit.

========================

All of these problems should be resolved in this PR: https://github.com/BattlePlugins/BattleArena/pull/104

I have been testing this for about two weeks now and have not run into any more issues or conflicts.

**Comment by RednedEpic** [comment]
I apologize for the lack of attention on this PR. I was out of town for a week and completely forgot of its existence. Give me a few minutes to look over it and I'll get back to you.

**Comment by Delfofthebla** [comment]
> 
> 
> I apologize for the lack of attention on this PR. I was out of town for a week and completely forgot of its existence. Give me a few minutes to look over it and I'll get back to you.

Hey no worries man, I'm just using my local build atm and it's working fine. I just wanted to get an official issue open since the purpose of my PR has kind of shifted away from the original intention.

**Comment by RednedEpic** [comment]
Merged.
