### ISSUE TITLE
API

### ISSUE THREAD

**Issue by Rocologo** [BattlePlugins/BattleArena#107]
Hi 

I am using your API to add support for BattleArena in MobHunting. Until now I have been using your maven repository 

http://rainbowcraft.sytes.net

but the server seems to be down? Has it been moved?

**Comment by RednedEpic** [comment]
Yes. Please use https://repo.battleplugins.org/artifactory/libs-release

**Comment by Rocologo** [comment]
Thanks.

**Comment by RednedEpic** [comment]
Apologies, accidentally put the wrong link there. While that link has all the jars you need, it also has a load of other stuff that you don't really need.

If you're looking for the one with just the BattleArena jars and any dependencies it may use, refer to: https://repo.battleplugins.org/artifactory/libs-release-local/. (just add the -local at the end of what is above)

**Comment by Rocologo** [comment]
Thank you. again :-)

**Comment by RednedEpic** [comment]
No problem.
