### ISSUE TITLE
/tourne create ERROR

### ISSUE THREAD

**Issue by SoraShiunin** [BattlePlugins/BattleArena#110]
Hello, recently started using Battle Arena and wanted to get into automated tourneys. Except wen I type /tourney create (arena name), nothing happens and error pops up.
Am I doing something wrong?
https://pastebin.com/JLZ0Q27X

**Comment by RednedEpic** [comment]
What version of BattleArena are you using?

**Comment by RednedEpic** [comment]
Just booted up a test server and had the same error. This command actually should not exist (from what I know) for tourney commands. What you instead should do is use the /tourney auto (arena name) or /tourney open (arena name).

Take a look at this page for more information:
https://docs.battleplugins.org/docs/ba/scheduling/tournaments

This should also cover how to set up an auto tournament with the specified arena type.

**Comment by SoraShiunin** [comment]
Alright. Thanks. I'm using the 3.9.12.13 version.
