### ISSUE TITLE
Problem setting an arena's region

### ISSUE THREAD

**Issue by YayaDuck** [BattlePlugins/BattleArena#112]
Hey, I have problems assigning a region to an arena using your plugin. Your plugin is amazing and has all the features anyone would nede for PvP gamemodes, but I have encountered a slight issue with the region selection. When I try to assign a region as a CTF map using the command /arena alter <name> addRegion, the plugin tells me that I need to have a region selected in order to perform the command, even though I do. I'm running a server on 1.15 with the BattleArena plugin and the ArenaCTF plugin.
Thanks for your help.

**Comment by RednedEpic** [comment]
If you haven’t read this already, this page explains regions in more detail: https://docs.battleplugins.org/docs/ba/arenas/regions.

If you’re still having issues, check console to make sure that there isn’t any errors. Also what version of BattleArena are you running? (/ver BattleArena ingame)

**Comment by YayaDuck** [comment]
Thanks for your reply.
I have discovered that the issued was caused by the unsupported version of WorldEdit that we used. (We used the 1.14 version because there is no 1.15 version yet.) This caused the region selection to not be detected by BattleArena.
