### ISSUE TITLE
Port BattleArena to the Sponge platform?

### ISSUE THREAD

**Issue by LGCMcLovin** [BattlePlugins/BattleArena#113]
Sponge has a certain lack of decent minigame plugin options, and i am a huge fan of battlearena. Given the fact i only run modded servers, i was hoping that a port to sponge could be done?

**Comment by RednedEpic** [comment]
You’re in luck! The rewrite is already being designed with multi platform compatibility (including Sponge) 😄.

**Comment by LGCMcLovin** [comment]
you...... are my hero

**Comment by LGCMcLovin** [comment]
oh and battleplugins.com down or? i get a cloudflare timeout warning

**Comment by RednedEpic** [comment]
> oh and battleplugins.com down or? i get a cloudflare timeout warning

battleplugins.org would be the correct domain.
