### ISSUE TITLE
Broken Signs - Capture the Flag & Free for All

### ISSUE THREAD

**Issue by Webman97** [BattlePlugins/BattleArena#114]
When creating signs for Capture the Flag and Free for All, the plugin shows that each sign is created successfully. However, the arena name does not show up under either. When clicking the "Join" sign, nothing happens. When clicking the "Leave" sign, players are able to leave the arena. These signs are not changing the color of the blocks their on, nor showing the amount of players in the arena at a time.

Please let me know if further information is needed.

**Comment by RednedEpic** [comment]
> When creating signs for Capture the Flag and Free for All, the plugin shows that each sign is created successfully. However, the arena name does not show up under either. When clicking the "Join" sign, nothing happens. When clicking the "Leave" sign, players are able to leave the arena. These signs are not changing the color of the blocks their on, nor showing the amount of players in the arena at a time.
> 
> Please let me know if further information is needed.

Is there any error in console?

**Comment by Webman97** [comment]
> Is there any error in console?

No.

**Comment by RednedEpic** [comment]
> > Is there any error in console?
> 
> No.

If you're using `ctf` between the brackets, use `capturetheflag` instead, or if it's the reverse, vice versa. Also, make sure you are specifying an arena on the third line (see [this page](https://docs.battleplugins.org/docs/ba/customization/signs) for more information).

**Comment by Webman97** [comment]
> If you're using `ctf` between the brackets, use `capturetheflag` instead, or if it's the reverse, vice versa. Also, make sure you are specifying an arena on the third line (see [this page](https://docs.battleplugins.org/docs/ba/customization/signs) for more information).

I can confirm I've tried all iterations and permutations of this. Hours of testing, for some reason it just doesn't seem to be working. Very odd.

**Comment by RednedEpic** [comment]
![image](https://user-images.githubusercontent.com/29153871/77030308-28cb0680-696c-11ea-94e4-d012fc27c8e3.png)
Seems to be fine for me. Make sure that everything in the arena is set up (e.g. you have all the waitrooms, flags, and spawns set) and that you can join with the normal join commands too.

**Comment by Webman97** [comment]
> Seems to be fine for me. Make sure that everything in the arena is set up (e.g. you have all the waitrooms, flags, and spawns set) and that you can join with the normal join commands too.

I'll test again and report back!

**Comment by Webman97** [comment]
Per your steps, I was able to resolve the CTF issue. I was missing a waiting room. However, my FFA arena is still not working. My FFA arena has waitrooms and spawns set, am I missing something else?

**Comment by RednedEpic** [comment]
> Per your steps, I was able to resolve the CTF issue. I was missing a waiting room. However, my FFA arena is still not working. My FFA arena has waitrooms and spawns set, am I missing something else?

Have you made sure that you're able to join it using the normal `/ffa join <name of arena>` command? If not, make sure that you are able to do that and then try to set up the sign again.

**Comment by Webman97** [comment]
> Have you made sure that you're able to join it using the normal `/ffa join <name of arena>` command? If not, make sure that you are able to do that and then try to set up the sign again.

Yes, I am able to join using the normal `/ffa join <name of arena>`

**Comment by RednedEpic** [comment]
> > Have you made sure that you're able to join it using the normal `/ffa join <name of arena>` command? If not, make sure that you are able to do that and then try to set up the sign again.
> 
> Yes, I am able to join using the normal `/ffa join <name of arena>`

Try using `[freeforall]` on the first line of the sign. If that's not working, try `[ffa]`.

**Comment by Webman97** [comment]
> Try using `[freeforall]` on the first line of the sign. If that's not working, try `[ffa]`.

I've tried both, same results. [ffa] does not work, [freeforall] works.

**Comment by RednedEpic** [comment]
Have you made sure the arena name was correct? Seems to be working just fine for me.
![image](https://user-images.githubusercontent.com/29153871/77219309-a759ac80-6b02-11ea-8eaa-d277970ac4b2.png)

**Comment by Webman97** [comment]
> Have you made sure the arena name was correct? Seems to be working just fine for me.

Using that exact syntax, it is not working. The arena name disappears after I create the sign. Am I missing a spawn? Waitroom? Etc..

**Comment by RednedEpic** [comment]
> > Have you made sure the arena name was correct? Seems to be working just fine for me.
> 
> Using that exact syntax, it is not working. The arena name disappears after I create the sign. Am I missing a spawn? Waitroom? Etc..

As far as I know if you're able to join with `/ffa join <arena name>`, it should show up just fine on the sign. Try creating a new ffa arena and see if the same problem persists.

**Comment by Webman97** [comment]
> As far as I know if you're able to join with `/ffa join <arena name>`, it should show up just fine on the sign. Try creating a new ffa arena and see if the same problem persists.

Will do! I'll let you know if this fixes the issue!

**Comment by Webman97** [comment]
I deleted the Free for All arena, created a new FFA arena, set 12 spawns/12 waitrooms, and placed the sign down:

1. [FreeForAll]
2. join
3. ffa-1

Same result...

**Comment by Webman97** [comment]
I threw the following in console when placing the sign down/trying to interact with the sign: https://pastebin.com/xmHJt5nU

**Comment by Webman97** [comment]
@RednedEpic Any updates regarding this issue?

**Comment by RednedEpic** [comment]
> @RednedEpic Any updates regarding this issue?

I've only briefly looked through the code, but the error could be caused if you don't have a world called `world`. Is this the case on your server?

**Comment by Webman97** [comment]
@RednedEpic I have a world called `world` on my server, so no. Now I get this message when creating signs:

![Untitled](https://user-images.githubusercontent.com/2503727/80859774-4361f200-8c31-11ea-8b28-201fa61f2484.png)

Considering other Arena & BattleArena plugins are not colliding in this regard (I was able to create all other signs with no issues), I assume the issue is with BattleArena specifically.

**Comment by Webman97** [comment]
I'm assuming this issue will not be resolved. Since I have not received a reply in over 8 months, I am closing this.
