### ISSUE TITLE
Battleplugins repo

### ISSUE THREAD

**Issue by Rocologo** [BattlePlugins/BattleArena#118]
Your repo seems to be down?

https://repo.battleplugins.org/artifactory/libs-release

**Comment by Europia79** [comment]
There's an alternative Maven Repository at
[http://rainbowcraft.sytes.net/maven/repository/](http://rainbowcraft.sytes.net/maven/repository/)

Also, you can use [BattlePluginsDev](https://github.com/BattlePlugins/BattlePluginsDev) to download all the run-time libraries & compile all the compile-time dependencies... all in a few easy commands:

```
git clone --recurse-submodules https://github.com/BattlePlugins/BattlePluginsDev.git
mvn install -f setup.xml
mvn -B archetype:generate -DarchetypeGroupId=mc.bp -DarchetypeArtifactId=server -DarchetypeVersion=test
git checkout -- pom.xml
mvn clean install
```

Hopefully this helps.  If not, lemme know what you're looking for.

**Comment by Rocologo** [comment]
Thanks very much. I have hooked into BattleArena from MobHunting, so I only need the repo to compile MobHunting.

I have made it so players dont get **MobHunting rewards** when a player kill another player in a battle. Plugins like BattleArena and MobArena usually do have its own rules for rewards and the players should not have double rewards or the benefit that they dont "really" die in a battle.
