### ISSUE TITLE
BattleArena doesn't work with FAWE 

### ISSUE THREAD

**Issue by Llamasquishy** [BattlePlugins/BattleArena#120]
Hi,

I receive the following error when using the FAWE wand to create a BA region:
"You need to select a region to use this command."

Using //pos1 and //pos2 produces the same result.

**Comment by RednedEpic** [comment]
From #121: wgResetRegion does not work either. Seems like BattleArena is not even recognizing FAWE.

**Comment by Llamasquishy** [comment]
FAWE Version:
1.15-144

BA Version:
3.9.16.4

**Comment by supawiz6991** [comment]
I believe this is because FAWE support was removed.
