### ISSUE TITLE
wgResetRegion doesn't work with FAWE

### ISSUE THREAD

**Issue by Llamasquishy** [BattlePlugins/BattleArena#121]
Hi,

I am unable to get the wgResetRegion option working with FAWE. It works perfectly with WorldEdit but I need the asynchronous capability of FAWE. I have tried using it with onJoin, onStart, onComplete, and onFinish.

**Comment by RednedEpic** [comment]
Can we consolidate this into #120?

**Comment by Llamasquishy** [comment]
> Can we consolidate this into #120?

If the root cause is related then definitely :)
