### ISSUE TITLE
BattleArena cnflicts whith animatedscoreboard and tab reborn

### ISSUE THREAD

**Issue by JoseLu1200** [BattlePlugins/BattleArena#125]
When you finish a game in any mode of the battlearena, the scoreboard is deactivated and if you deactivate it and reactivate it, when you change the world the scoreboard does not change to that corresponding to that world, and with tab reborn when you finish a game the section is removed ping

**Comment by supawiz6991** [comment]
Apologies for the lengthy delay in responding. As for your issue, unfortunately, the current iteration of battlearena won't have fixes for it. However, the dev team is working on a complete rewrite of the plugin from the ground up. I do not have an eta to share right now but hopefully it should work ok with these plugins.
