### ISSUE TITLE
It looks like signs for join and leave are broken.

### ISSUE THREAD

**Issue by dudematthew** [BattlePlugins/BattleArena#126]
![image](https://user-images.githubusercontent.com/28755235/87669865-022ca900-c76f-11ea-968f-ab9c39f25de3.png)

After setting sign using this template:

[type]
join 
arena_name 
nothing 

The result is as is shown in the foto.

Need fix asap.
Thank you.

**Comment by supawiz6991** [comment]
Apologies for the lengthy delay on responding. 
As for signs, there is some known issues with signs 

- [ctf] stops working but [capturetheflag] doesn't
- Signs may be broken after server restart
If you still need help with this, either update here or join us on discord in our #plugin-help channel -> https://discord.gg/AXm6uNfu
