### ISSUE TITLE
Getting a warn

### ISSUE THREAD

**Issue by SirCraftypants** [BattlePlugins/BattleArena#129]
Just installed for first time, reloaded and got this Warn

https://paste.helpch.at/eqesotidex.md

Paper Spigot 1.16.5
Client: Minecraft.

**Comment by supawiz6991** [comment]
Hi,
This is a known issue BUT it does not impact functionality and can be safely ignored. The startup error will be fixed in a future update. An eta for said fix is not available at the moment.
