### ISSUE TITLE
Help in the console inconsistent with documentation and actual behaviour 

### ISSUE THREAD

**Issue by oskarkk** [BattlePlugins/BattleArena#130]
`/arena help` lists a command `/arena add`. This command gives an error: `This command doesn't exist! /arena help for help`. I guess that it was left after some update which changed `add` to `create`?

There's also another thing that pops up but doesn't work:

![image](https://user-images.githubusercontent.com/16339637/118216434-cab48900-b473-11eb-8d30-ae5c8ccb8c20.png)

Command completion suggests `/arenaEdit` command, which when executed looks like it's not existing at all.

Version: BattleArena_v3.9.17.0

**Comment by supawiz6991** [comment]
This is a known issue with the current iteration of the plugin which is very old. Currently, the dev team is working on a complete rewrite of the plugin from the ground up which will not have this issue.

**Comment by oskarkk** [comment]
Where can I find the version that is in development?

**Comment by supawiz6991** [comment]
It is not yet available to the public just yet. We will put out an announcement on our discord server when it becomes available.
If you are not already in our discord you can join it here -> https://discord.gg/xj56QXHy
