### ISSUE TITLE
Set health=20 on Start does not work

### ISSUE THREAD

**Issue by Poldi-de** [BattlePlugins/BattleArena#131]
When a player has 4 hearts in normal gameplay and joins a game, he will start with 4 hearts, even if
> health=20

is set, which should give full health on game start and restore it when the game is finished. 
(PaperMC 1.16.5, Default Config, No other plugins)

**Comment by supawiz6991** [comment]
Troubleshooted this and confirmed that it is a bug. 
1. If player enters arena with less that 20 health and health: 20, players health is not increased. Same goes for hunger.
2. If player enters arena with full hunger and hunger:20 , hunger is reduced to half.
Issue forwarded to dev's.
