### ISSUE TITLE
*PLEASE READ BEFORE CREATING AN ISSUE* KNOWN ISSUES LIST! 

### ISSUE THREAD

**Issue by supawiz6991** [BattlePlugins/BattleArena#132]
Hi Everyone!
Below is a list of known issues that we are aware of in the latest version of Battlearena as of 1.16 but could exist in older versions. If your issue is on this list, please do not open an issue about it as we are already aware of it.

Confirmed Issues:

- health config directive does not work.
- hunger config directive does not work as expected. Players with full hunger will be reduced to half when hunger: 20. Outside of that hunger does not appear to function.
- matchForceStartTime does not work outside of config.yml
- armorTeams does not work.
- teamconfig RGB settings do not work.
- Reload command is broken. You must restart your server for config changes to take effect.
-  enchantments not working. Between the change in naming structure and addition of new enchants, this function for items is broken.
- Items not being given. Due to a change in the item naming structure as well as the addition of new items, some items cannot be given in battlearena.
- Signs. There are multiple issues with signs from straight up not working in some conditions to breaking after server restart).
-  Scoreboard lag. Scoreboard may cause significant lag spikes in certain circumstances. Those specific circumstances are unknown as not everyone experiences this issue. Also, servers that have low memory and processing capabilities may be more liked and more severely impacted by this issue.
- Potions are broken. You can get around this by using docommand in your gamemode's config.
- command /tourney start, when used after /tourney open, is broken and reports "No open events". the command /tourney auto appears to still work and should be used for now.

Unconfirmed Issues:

- players losing inventory. We've seen cases of this and in most of those the issue is due to plugin conflict, inventory management plugins being dumb or moving between worlds. That being said, there have been some rare cases where players have lost inventories 1 in X times they go through the arena. We have not been able to determine the root cause of these rare cases and as such have deemed this an unconfirmed bug for now. This is the only bug on this list that it is acceptable to open a new issue about so we can continue to investigate.

This list will be updated as items are fixed or new ones added.

**Comment by clovisd** [comment]
Closing for fresh start. :)
