### ISSUE TITLE
Potions do not work; give 'uncraftable potion'

### ISSUE THREAD

**Issue by henriz** [BattlePlugins/BattleArena#133]
L.S.,

I'm trying to modify the classes so that players have a potion of poison. Potions do not appear to work. Even with the default classes.yml, players get potions with a name 'uncraftable potion'.

**Comment by supawiz6991** [comment]
Hi,
This is a known bug caused by the change in item/enchantment name scheme. The only work around at this time would be to use (in onspawn)
doCommand:
- console give player <potion of choice>

replace <potion of choice> wiht something like splash_potion{Potion:"minecraft:strong_harming"} 1

**Comment by henriz** [comment]
Ok, will do, thanks :)

Forgot to mention I'm using MC 1.16.5, and the latest plugin version.

**Comment by supawiz6991** [comment]
yeah, the bug is current in the latest version...unknown how far back it goes without further testing.

**Comment by supawiz6991** [comment]
Closed accidently. Leaving open to track bug.
