### ISSUE TITLE
Players can enderpear out of arena

### ISSUE THREAD

**Issue by henriz** [BattlePlugins/BattleArena#134]
I want my players to have enderpearls inside the arena. This works fine. I set it so they can't leave the arena. This also works.

However, they can still enderpearl out of the arena.

I made a region using worldedit region, added it to the arena.

**Comment by supawiz6991** [comment]
Is your intent to only allow the enderpearl to teleport them within the arena?

**Comment by henriz** [comment]
yes. Basically for my kids I made a map which is ment to be pvp/battle only. I created this arena:
[img]https://i.imgur.com/TF6yhEB.png[/img]

The goal is to have them be able to enderpearl within the arena but if they throw a pearl over the edge they have to teleport like if they hit the edge.

**Comment by supawiz6991** [comment]
in your gamemodes config under onspawn try adding wgNoLeave.
Link to our wiki with more information on this -> https://docs.battleplugins.org/docs/ba/arenas/regions#adding-regions-with-worldguard
