### ISSUE TITLE
Error in logs

### ISSUE THREAD

**Issue by SonyGamer270** [BattlePlugins/BattleArena#140]
Hello, I have a problem, I am using spigot 1.21 and I am getting an error.

https://pastebin.com/75ne53gv

**Comment by supawiz6991** [comment]
Spigot is not currently supported. The rewrite version only supports paper at this time.

**Comment by SonyGamer270** [comment]
Will it ever be compatible with the spigot ?

**Comment by Redned235** [comment]
This is not planned.

**Comment by SonyGamer270** [comment]
Shame
