### ISSUE TITLE
Abusable glitch with MobArena

### ISSUE THREAD

**Issue by PetKCH** [BattlePlugins/BattleArena#15]
So I made a duel arena on my server, and problem is, players challenge someone for /duel, then they join mob arena, and send other player a message to accept the duel upon which BattleArena saves mobarena inventory as their inventory and they get to keep those items after playing battlearena match. Is there any way to disable commands usage like /ma while challenging someone to a battle?? Please help, thanks in advance

**Comment by Zach443** [comment]
On line 35 or so in the config.yml for BattleArena there is an option called <i>disabledCommands:</i> 
Add whichever commands are being abused in that list. After that, restart your server and player should no longer be able to use those commands while in the queue, or during a match.

**Comment by Laos1996** [comment]
I haven't explained properly, my bad, I did this already
What they do is following:
They /duel "someplayer"
While they wait for that player to type /duel accept
They join /ma join somearena and pick a kit
Then they message that player to accept the duel
They go into queue for duel, and it saves mobarena kit as their default kit
They duel, mobarena kicks them for leaving mobarena, when they rejoin, BattleArena2 gives them mobarena kit as default kit they had before joining it

**Comment by Europia79** [comment]
/plugins/BattleArena/config.yml

There is an option called **disabledQueueCommands: []** 

Put ```disabledQueueCommands: [ma]```

The node ```disabledCommands``` is only in effect once the match actually starts. The ```disabledQueueCommands``` is for BEFORE the match starts... when players are in the lobby.

**Comment by Laos1996** [comment]
And this is what I did already;
"# What commands should be disabled when the player is inside of a queue, but not in a match, (use ['all'] to disable everything)
disabledQueueCommands: [home, spawn, payhome, warp, watch, sethome, ma, f, factions]"

I think you misunderstood me, before the other party accepts with "/duel accept" the player which challenged him is free to do "/ma join" and can do the glitch...only AFTER he types /duel accept they go into queue, NOT before, thats why this is an issue I cant fix anyhow

**Comment by Europia79** [comment]
/plugins/BattleArena/competitions/DuelConfig.yml

i'm going to try changing some options for Duel to see if I can force the player doing **/duel <opponent>** to join a queue...

if this doesn't work. I would suggest separating your survival world from your arenas-world... That way, if someone does the glitch... it doesn't help them... they're still in the Arenas-World... not the Survival-World

**Comment by lDucks** [comment]
@clovisd is this resolved?

**Comment by graywolf336** [comment]
Just to comment, seems to not cancel commands which aren't true "commands" but ones that are only handled via listening to all commands and using that. For example, I've tried to disable Towny Chat commands inside the arena and BattleArena told me I can't use it but the chat still showed up. At the moment I'm not sure if that's an issue with Towny Chat or Battle Arena, but I do know that World Guard cancels the same command.
