### ISSUE TITLE
- teleportWaitRoom causes woolhead not to work

### ISSUE THREAD

**Issue by tara81** [BattlePlugins/BattleArena#17]
- teleportWaitRoom in config causes wool head to stop working until player dies

**Comment by Europia79** [comment]
From reading the code, I believe BattleArena won't use wool heads if there's only 1 player on a team. To override this, you have to use alwaysWoolTeams.

i'll have to look into it tho.

**Comment by lDucks** [comment]
@Europia79 is there a resolution for this? Are we considering this a non-issue?
