### ISSUE TITLE
Giving god onLeave

### ISSUE THREAD

**Issue by CassandraWipf** [BattlePlugins/BattleArena#21]
Is there a way to give Godmode back onLeave? I have my staff in god and would like them to get it back after they finish in the arena. 

v3.9.9.18

**Comment by Zach443** [comment]
Currently there is only a way to restore op.

**Comment by clovisd** [comment]
I think you meant god Zach. :3

**Comment by Zach443** [comment]
@clovisd Uh, no. I meant what I said :P

**Comment by clovisd** [comment]
Wups. I read "There is no way to restore op". My bad.

**Comment by lDucks** [comment]
Closing as this is a config question that seems to have been either resolved or forgotten.

**Comment by Europia79** [comment]
i believe Godmode is something specific to Essentials. 

If someone wants to fix this, i believe Alkarin has an EssentialsController for manipulating Godmode. We would just have to add the configuration option, and execute the controller in ONLEAVE transition.
