### ISSUE TITLE
Parkour.

### ISSUE THREAD

**Issue by Scorpionvssub** [BattlePlugins/BattleArena#27]
> On the use of `/pk join Jump!` i already won as its checking for multiple players it seems and if 1 is left its done for...

I added compatible arenaparkour to the server and used the config it said to use for solo runs.

I made a solo world within the games server A void world, made a small box of quartz with a fire floor incase people fall, since there are no respawns if you fall below 2-3 blocks from where u should land, and only respawn on death. I done the command /parkour create Jump! then set my checkpoint with /pk acp 2 somewhere on a diff block and /pk avp(victory) 1 on a block about...10 blocks away from the starting point. On join it starts a timer as if to have it compete against others while a stand alone was ment to happen you just join and run for yourself, not to compete. On the use of /pk join Jump! i already won as its checking for multiple players it seems and if 1 is left its done for...

I didnt change the config in any way except for:

Let everyone play solo
Copy this ParkourConfig.yml and paste into your ArenaParkour/ParkourConfig.yml
Afterwards just do /pk reload

http://dev.bukkit.org/bukkit-plugins/arenaparkour/#comments

Here an add-on on the config i have: http://pastebin.com/2gjM7Myk

For an even better example just join us.

So to reproduce: Make a void world with mutliverse
Create a box of...24x26 and 11 in heigth
![image](https://cloud.githubusercontent.com/assets/12249763/7691430/8bc15de8-fdba-11e4-8184-bc29efa8448a.png)
Type in /pk acp Jump! 2 where the gold pressure plate is 
Then /pk avp Jump! 1 to the blocks 2nd block away from the creeper

Added in is a picture of the inside. on the 2x2 you spawn, the golden pressure plate is a checkpoint and the block on the far right (2nd block to the right of the creeper) is the victory block. 

This incase you wanna remake this entire arena to really reproduce

For more questions just ask :)

**Comment by Zach443** [comment]
That is a pretty creative use of custom arenas to get around the bugs in ArenaParkour! I would however suggest that you post this on our discussion section on Spigot. That would probably me a more appropriate place.

**Comment by Scorpionvssub** [comment]
then blame the guy that gave me the link on your IRC.

**Comment by Europia79** [comment]
@Scorpionvssub 

i'll look into what's going on. 

Btw, The pastebin was removed. What was the contents of it ?

http://pastebin.com/2gjM7Myk

@Zach443 

> That is a pretty creative use of custom arenas to get around the bugs in ArenaParkour!

What do you mean custom arena ? What bugs ? This doesn't appear to be a custom arena (an arena defined only by a *Config.yml file)

> I would however suggest that you post this on our discussion section on Spigot. That would probably me a more appropriate place.

The github issues page is fine so that we can keep track of it easier. Eventho, it's not specifically BattleArena, it does involve a BattleArena extension.

**Comment by Zach443** [comment]
@Europia79 If he created his own yml file with a new arena that counts as a custom arena.. I'm not really sure what else you would call that. Also, ArenaParkour has its own repository, and this is more of a user workaround than a bug.

**Comment by Scorpionvssub** [comment]
@Europia79 The pastebin was contents of the config which were default. all i did was /pk create and set my checkpoints the way the site told me to.

**Comment by Europia79** [comment]
@Scorpionvssub 

For ```ParkourConfig.yml```, try using ```victoryCondition: NoTeamsLeft``` instead of Custom, and see if that works.

**Comment by RednedEpic** [comment]
Closing. If anything else comes up or someone else encounters a similar issue, please create an issue at the ArenaParkour repo: https://github.com/BattlePlugins/ArenaParkour/issues.
