### ISSUE TITLE
restoreItems apprears not to be working?

### ISSUE THREAD

**Issue by PetKCH** [BattlePlugins/BattleArena#35]
Here is my current config for Duel http://pastebin.com/XygVj91a
I have tried various ways, placing store & restore Items variable everywhere, and it NEVER restores items, not only that, but players often get placed on waypoints where they were in previous duel...please help, any dev version I should maybe use?

**Comment by Zach443** [comment]
In your **onEnter** put storeAll and in your **onLeave** put restoreAll . That should do the trick. Take note from the default DuelConfig, here: https://github.com/BattlePluginsDev/BattleArena/blob/master/default_files/competitions/DuelConfig.yml

**Comment by Laos1996** [comment]
Tried that too, and it doesent work, same things happen! :/

**Comment by Zach443** [comment]
Are you sure? Last time we were testing stuff everything was working fine. Jump on IRC and we can chat a little bit.

**Comment by Laos1996** [comment]
Just tried it, when we join arena, we get items which he had before arena, after we finish, we dont get any items back

**Comment by infered5** [comment]
Bumping because I have the same problem

**Comment by RednedEpic** [comment]
If you're still using BattleArena and experiencing this bug, please feel free to comment here stating that you're still having this problem or message us here https://discord.gg/tMVPVJf on Discord (we don't have IRC anymore) . I have never experienced this bug before (as a user of this plugin) and storing/restoring items in inventories appears to work just fine for me.
