### ISSUE TITLE
arena alter (addregion)

### ISSUE THREAD

**Issue by MatthiewL** [BattlePlugins/BattleArena#36]
sorry for my bad english ;,; 
i want to add a region in my arena
when i do /ra alter lava addregion
i have select a region with we 
arena battle put in the chat
ra setarenaoption <arena> <gamestage> <option> [value]: you need to specify a game stage 
ra setarenaoption <arena> <gamestage> [value] you need to specify a alterparamoption

**Comment by RednedEpic** [comment]
Closing old issues, if you are still having troubles, please feel free to message here https://discord.gg/tMVPVJf on Discord and we'll be happy to help you out :).
