### ISSUE TITLE
KDR round to 2 decimal places!

### ISSUE THREAD

**Issue by helptiger** [BattlePlugins/BattleArena#39]
Pls round the KDR to 2 or definable decimal places. It's not useful to display a KDR with more decimal places like 1.26748238294

**Comment by Zach443** [comment]
Oh wow.. I have seen this in other messages (such as the one that tells you how much health your opponent has left when you lose). I'm actually rather surprised that alkarin didn't think to round the decimals to something easier to read/more appropriate.. I will take a loot at this and see if I can fix it.

**Comment by Europia79** [comment]
@helptiger 

How are you accessing the KDR ? Via a command ? Via a php script ? Or via some other method ?

**Comment by helptiger** [comment]
with command /pvp

**Comment by Europia79** [comment]
@helptiger 

This is fixed in BattleTracker v2.5.9.2

download:
http://dev.bukkit.org/bukkit-plugins/battlearena2/

code changes:
https://github.com/BattlePlugins/BattleTracker/compare/db39c32cc16c...f94909a85a67

Thanks for reporting the issue !
