### ISSUE TITLE
Custom Lore on Class Items

### ISSUE THREAD

**Issue by graywolf336** [BattlePlugins/BattleArena#41]
As a user, the ability to give custom lore, or descriptions, on items in classes would be amazing. Colors, multiple lines, and utf8 characters support is essential for the optimal experience and customization of classes.

**Comment by graywolf336** [comment]
If this and #40 are already possible, maybe use these as a reminder to update the wiki. :) as I couldn't find anything on there about support for this.

**Comment by Zach443** [comment]
I'm on mobile right now so I can't get you a link, but search for Item Syntax on the wiki. You should find what you're looking for.

**Comment by graywolf336** [comment]
Found it: http://wiki.battleplugins.org/Item_Syntax now my suggestion would be too add a link to that page on the classes page. :)

But on the lore, I don't see how to do more than one line. And I'm mobile as well at the moment so I can't test it, but I want to guess that I can have multiple lore="" to get more than one line? Another question which arises after looking at that page, as it's not directly clear, does the lore support color codes?

**Comment by Zach443** [comment]
You might be able to do a line break with \n, however I'm not really are of that would work. It might not die to the way BattleArena parses the strings, but it's worth a shot.

**Comment by graywolf336** [comment]
I will be able to test it tonight, but if it's using new lines then I doubt it'll work either since the last time I tested new lines in lore it didn't work as they had to be separate strings since the lore is a List.

**Comment by Zach443** [comment]
@graywolf336 any update on this?

**Comment by graywolf336** [comment]
I haven't tried since my last update. I no longer run my server either, so
I can't exactly test..

**Comment by Zach443** [comment]
Ok, no worries. I'm just going through all the issues, and noticed there was never a response to this.

**Comment by RednedEpic** [comment]
Going through old issues right now, as it appears you found a solution, I am closing this. If you have any problems (or anyone else for that matter), please feel free to message us here https://discord.gg/tMVPVJf on Discord and we'll be happy to help.
