### ISSUE TITLE
[Suggestion] Chests with random items

### ISSUE THREAD

**Issue by CyberStarLight** [BattlePlugins/BattleArena#45]
I think random items can really help many game types and arenas, and can help imitate minigames like skywars, hunger games, etc.

One way I think it can be done is to have a command like "/arena [id] addItem [item name] [chance]"
that will add items to a list.
and an arena option of "itemsPerChest=2-5"
when the match starts look for all chests in the region and add to them 2-5 items from the list using the % chance.

I think it will be nice if this will NOT reset/empty the chest, just add to them, so we can add special rare loot in some hidden chest (say, enchanted diamond sword) and it would stay there.

**Comment by Zach443** [comment]
You can already do something very similar to this with chest spawns. You can set specific items to spawn, although all of them will be spawned in that chest every time. There is no chance element to it. A chance feature could be added, but here is how you could use the existing feature: http://wiki.battleplugins.org/BattleArena/Spawns#Chest_Example

**Comment by Redned235** [comment]
This is now possible using the [PhatLoots](https://modrinth.com/plugin/phatloots) plugin, which has integration for BattleArena.
