### ISSUE TITLE
Restore Items works Most of the time

### ISSUE THREAD

**Issue by voigtman** [BattlePlugins/BattleArena#49]
In the config I have this line set to
numberSavedInventories: 10
And once a player reaches this limit, their inventory doesn't always restore. Often they have to enter a second duel and win it to have their inventory restored from the previous duel. 

My setup includes
BattleArena 3.9.10.4
Spigot 1.8.8
WG 6.1.1 Snapshot
PlotSquared 3.1.3
mcMMO 1.5.03
and PvPManager 3.0 snapshot -b143

**Comment by RednedEpic** [comment]
Can confirm this bug still exists, however the true cause of this is still unknown.
