### ISSUE TITLE
Team invite acceptance Commands are hosed/Command help text wrong.

### ISSUE THREAD

**Issue by supawiz6991** [BattlePlugins/BattleArena#50]
(Originally Reported by: Verv on 8/29/15 @ 1:50pm ET)
Team Commands seem to have changed unexpectedly at some point and the command message wasn't updated (in a while). Here's the Dirt:

1. (Most Important) when accepting team invites the command use to be /team accept. this command no longer works. I found that /team join or /arenateam join work. /team accept is the preferred as it makes sense since your accepting an invite.

2. The command help message is incorrect. Currently for the team creator as well as the invite recipient the help text says that to accept an invite the invitee will need to do /team add. This command does not work and to my knowledge hasn't worked since I started using the BattlePlugins 1-2 years ago.

**Comment by Zach443** [comment]
Thanks for making the issue for this, I'll see what I can do :)
