### ISSUE TITLE
Suggestion: Some Uniformity accros yml and wiki related things. 

### ISSUE THREAD

**Issue by Vervatwala** [BattlePlugins/BattleArena#53]
Firstly I just want to clarify that even before writing this post 
1. I understand this plugin has changed and has multiple developers working on it
2. That I dont at all intend this to be rude/ demanding.
3. I am coming from a Non-developer standpoint and I refer to the Wiki and other yml files for reference. 

Hello! Recently been attempting to Edit some of the Competition yml files on the server, and since they were from a old version and didnt want to risk using something outdated I took a fresh competitions folder from the JAR and started working on that. 

However what I have found is the following: 
1. In the default folder (competitions) the format of the different competitions are written differently (example http://imgur.com/rFm6N1N and http://imgur.com/6gWiSsJ) 
and even though I know they achieve they same thing when I am looking though the different examples of competitions It can be confusing of what is correct and what isnt. 
If it could be possible to write them all in the same style of writing and even just ##comment the other options out I feel that could be a huge help! 
1. Again going along with the format thing, in Arena there is matchtime: 180 and in Battleground timing: {}
   I understand the correct way to use that is 
   timing:
    matchTime: 180
   I found this out within the IRC (thank u Supa and Euphoria) but again I feel like that should be uniform with the Wiki and YMLs 
2. Some options shown in places and others not: Examples I have here are on [this page](http://wiki.battleplugins.org/BattleArena/Custom_Games) the  line I am looking at is "joinType: Queue" and apart from that one page there isnt much info about it nor is that line present in the defaultConfig.yml
3. Stage Options consistency. I understand there are a lot of options when it comes to the different stages of the Match/Arena etc. However when configuring a YML it can be very confusing, just as an Example Lets say people have their items stored before a game and are givin items in match, Do we have to use the option [RestoreALL] during OnLeave or OnComplete ? Or is it such that if a person quits a game he isnt Completing the match so his items couldnt be retrieved? 
   There are some (like OnFinish ) that are listed in the Wiki but not in the default config.yml? 

Ik I have just been going on and on, but I hope you all know I am just trying to help out as much as I can, despite not knowing much coding-wize, I just feel if this uniformity for options already there are uniform it makes adding more and keeping track of them a lot easier. 
I have prob missed out or messed some point up but feel free to ask me on here or the IRC 
Cheers! 
Verv

**Comment by Zach443** [comment]
Thanks for the input verv! I have started to notice little inconsistencies such as the ones that you have pointed in BattleArena as well. I will be working to bring unity to the all of the (many) YAML files. My goal is to make sure everything across all places (wiki, GitHub, default configs, etc) has matching formatting/options so that confusion can be avoided for everyone involved.

**Comment by clovisd** [comment]
New Docs, New Plugin (full rewrite), so closing this legacy issue. :)
