### ISSUE TITLE
JoinPhase does not work 

### ISSUE THREAD

**Issue by hsombini** [BattlePlugins/BattleArena#58]
Hello,

I'm trying to use JoinPhase but I think that's not working as it should, this is my match config: http://hastebin.com/ovixeguwit.sm
1. Players can still Queue this match!
   _Expected behavior: Players cant Queue a JoinPhase competition_
2. " /guerra auto ArenaXX interval=30" announces the JoinPhase match as it should, but it never broadcast it again after 30 seconds. It's also printing "Participantes on the match", that should be printed only when the match began
   _Expected behavior: It should broadcast every 30 seconds until the match starts_
3. After the JoinPhase started, players who types "/guerra join" goes straight to the Queue of this competition
   _Expected behavior: Players goes to the JoinPhase match, the match will start only when the announce time is over_

There's no error on the console though
PS: The expected behavior is based on 3.7 version

**Comment by Europia79** [comment]
@hsombini 

i don't know if you got my messages in IRC, but according the code, it looks like this is an old, un-supported feature... but if i get the 3.7 JAR with the expected behavior then i'll investigate further.

Email it to me at Europia79@hotmail.com

**Comment by hsombini** [comment]
@Europia79 I've sended you my BattleArena 3.7.9.9.1 version with a already configured JoinPhase match.

Thanks for your response!

**Comment by RednedEpic** [comment]
Been quite a while, but if you're still having problems with this or anything, please feel free to reply to this issue or message us on Discord here https://discord.gg/tMVPVJf.
