### ISSUE TITLE
Does not load with WorldGuard 6.1 

### ISSUE THREAD

**Issue by 916253** [BattlePlugins/BattleArena#59]
When WorldGuard 6.1 is in the plugins folder, BattleArena (and its child plugins) are unable to load

**Comment by Zach443** [comment]
That's reaallly vague. Can you put some errors in a pastebin and/or provide some more info?

**Comment by Europia79** [comment]
@916253 

link your log file. i would like to see the entire startup so that i can check all the errors (not just the BattleArena ones).

**Comment by Europia79** [comment]
I'm going to assume he was using an old version of BattleArena that didn't support WorldGuard 6.1
