### ISSUE TITLE
Nothing but FFA works?

### ISSUE THREAD

**Issue by AnHonorableHobo** [BattlePlugins/BattleArena#64]
I have everything set up correctly for battleground/arena/skirmish and everything. But yet the only one that actually tp's players and counts when they are dead for a victory is FFA. This is my config for Skirmish

Skirmish:
  command: sk
  prefix: '&b[Skirmish]&e'
  gameSize:
    nTeams: 2
    teamSize: 1
  nLives: 1
  victoryCondition: LastManStanding
  times: {}
  tracking:
    database: arena
    rated: false
    useTrackerMessages: false
    announcements: ### Override the match victory announcement as the event has one too
        onVictory:  [ dontannounce ]
    defaults:
        options: [woolTeams]
    preReqs:
        options: [teleportWaitRoom]
    onEnter:
        options: [storeAll]
    onLeave:
        options: [restoreAll]
    onJoin:
        options: [ announce ]
    onOpen:
        options: [pvpOff]
    onPrestart:
        options: [pvpOff, teleportWaitRoom]
    onStart:
        options: [teleportIn, woolTeams, pvpOn]
    onComplete:
        options: [teleportOut]
    onDeath:
        options: [randomRespawn, keepInventory]
    onSpawn:
        options: [enchants, health=20, hunger=20]
        enchants:
            - speed:2:900
    winner:
        options: [enchants]
        enchants:
            - speed:1:300
            - resistance:1:300

It wont teleport people to any waitroom i have set, nor will it tp them to their spawn, nor will it count kills. Anyone know what is going on?

**Comment by Zach443** [comment]
Paste your other configs (Arena, BattleGround, whatever else doesn't work) using a paste service such as pastebin, [paste.battleplugins.com](http://paste.battleplugins.com)

**Comment by AnHonorableHobo** [comment]
http://pastebin.com/3MuWddNq

**Comment by AnHonorableHobo** [comment]
Is that good?

**Comment by RednedEpic** [comment]
I know it's been a bit over 3 years now, but if you're still having problems with this, please feel free to message us on Discord here https://discord.gg/tMVPVJf and we'll be happy to help you out.
