### ISSUE TITLE
restoreAll not working.

### ISSUE THREAD

**Issue by andrewleppala** [BattlePlugins/BattleArena#65]
BattleArena2 v3.9.10.4
Spigot 1.8.8 build #45
Arena config: http://pastebin.com/e8cc71Zd (ignore notes, was a misparse)
Step by step:
- Player with stuff enters game
- Inventory supposedly gets stored
- Player can either leave the waitroom or go on with the match, inside the waitroom the inventory is empty
- on leave and return to the server, their inventory should return, but does not
- on game start, inventory does not restore when it should. Also the woolhead doesn't appear until first death, but not a real problem.
- on game leave at any time, be winning, losing, running out of lives or quitting, the inventory is lost forever and not restored

When I look in my uuid.yml file under stored inventories, all I see is a nether star, although the timestamp is for when I've been testing. Please help, will provide any extra info you need if I haven't already.

**Comment by infered5** [comment]
bump?

**Comment by RednedEpic** [comment]
Fixed in latest version, there were some bugs within the inventory serialize class.
