### ISSUE TITLE
Nametags still show when players use invisibility potion

### ISSUE THREAD

**Issue by c0wg0d** [BattlePlugins/BattleArena#70]
We use the option alwaysTeamNames so it's easy for players to tell who's on their team and who's on the other team.  This option appears to override default Minecraft behavior in regards to invisibility potions.  Can you please hide the player's nametag when they drink/splash a potion of invisibility?

**Comment by tara81** [comment]
A suggestion could be to use magicspells to allow the player to hide instead of a potion. (Just an idea, I use a vanish spell for my ninjas)
