### ISSUE TITLE
Problem with pom.xml

### ISSUE THREAD

**Issue by Serux18** [BattlePlugins/BattleArena#73]
https://i.gyazo.com/4403ae1c087e6f23c2e3d230d2fc7510.png

This is the error I get when trying to compile the plugin in maven

**Comment by Europia79** [comment]
https://github.com/BattlePlugins/BattleBukkitLib

You need to build BattleBukkitLib v2.4.1 first... then you're good to go.

**Comment by Europia79** [comment]
I uploaded BattleBukkkitLib v2.4.1 to my maven server. You should be able to build BattleArena now
