### ISSUE TITLE
Errors when leaving matches .

### ISSUE THREAD

**Issue by tara81** [BattlePlugins/BattleArena#74]
Version Battlearena : v3.9.10.15
Spigot: 1.9.2
bpermissions: B: v2.12 Beta 18 for 1.9 Apr 04, 2016

Gta is my custom arena match.

http://pastebin.com/V14wV6Nf

Also happens in all other minigames: (snd)

http://pastebin.com/uEQQDDp0

**Comment by Europia79** [comment]
it's a bPermissions error

**Comment by tara81** [comment]
okay thanks, mentioned it to bpermissions author . He agrees.
