### ISSUE TITLE
Signs

### ISSUE THREAD

**Issue by SeDark** [BattlePlugins/BattleArena#76]
Please implement custom signs.
Like:

https://i.gyazo.com/c0948397ada1679fee0398c09370e94e.png

**Comment by Zach443** [comment]
There is actually a bug where if you create and Arena sign, break it, then put another sign in the same spot the new one will still function as an arena sign. Essentially this allows you to make your signs however you would like. Yes, it is still a bug, but people have found it useful so we have never fixed it.

**Comment by Serux18** [comment]
What I meant is that you can customize the lines of a sign..

**Comment by Zach443** [comment]
That's what I'm saying. If you create the default arena sign then break it, all you have to do is put another sign in its place. You can put whatever you would like on the new sign and it will work when you click it.

**Comment by Serux18** [comment]
But don't show how many people would show lack to enter the arena, for example.

**Comment by Zach443** [comment]
You are right, there isn't full functionality which would be nice. I will open this back up for future reference I suppose.

**Comment by RednedEpic** [comment]
Will hopefully be implementing sign customization in the next couple weeks (same with BattleTracker too).

**Comment by RednedEpic** [comment]
Accidentally referenced the wrong issue in 8c13281aa6061480cb37a8b303787530821efb02, but that commit closes this, since custom sign functionality is introduced with a custom block attachment feature.
