### ISSUE TITLE
Kits

### ISSUE THREAD

**Issue by ghost** [BattlePlugins/BattleArena#78]
/arena join <kit> to i can make my players click on a sword and opens a GUI then they click which pvp type they want to play like badlion/kohi (also picks random map)

**Comment by RednedEpic** [comment]
BattleArena does not support custom GUI's. If you want a player to have a GUI open when they join an arena, you'll have to install a GUI plugin and force them to run the command when they join an arena. If you're still having trouble with this, please join our Discord here https://discord.gg/tMVPVJf and we'll be happy to help you.
