### ISSUE TITLE
Death not registering

### ISSUE THREAD

**Issue by tehrenderr** [BattlePlugins/BattleArena#81]
After a player dies in an arena sometimes they are not teleported out because of the death event glitching out (minecraft bug) and then they are stuck in the arena without any commands. I tried putting enabledcommands suicide and kill but It still doesn't allow them to do it.

**Comment by Europia79** [comment]
Can i see your entire server log ?

**Comment by tehrenderr** [comment]
The server log doesn't show anything. No errors with battlearena and no death event errors. It just happens randomly and then a player gets stuck in the arena. The bug would be fine but for some reason /suicide and /kill don't work in the arena even though I have it enabled. I don't think sub commands work still even with the update you gave me. My config still has to be [arena, list] instead of [arena leave, list]

**Comment by Zach443** [comment]
You said the death event not getting called correctly was a bug in minecraft, care to elaborate on that?

**Comment by tehrenderr** [comment]
I'll message back when I get a video so it can better show the issue. 

Another thing I discovered is that whenever I set the y offset value to above 0.0 it prevents the players from spawning in the ground sometimes when they ENTER an arena but it also does the y offset value when they are EXITING the arena and that can be used to glitch bases because it sends them upwards 1-3 blocks.

**Comment by tehrenderr** [comment]
Alright a player was able to replicate it. It only respawns you in the arena when you have a regen potion enabled at the time of death. Let me know if you guys can replicate it.

**Comment by tehrenderr** [comment]
Were you able to replicate the issue?

**Comment by tehrenderr** [comment]
https://www.youtube.com/watch?v=flmyOReBXIc&feature=youtu.be
Here is a video of it happening, they are stuck in the arena afterwards and they can't use any commands.

**Comment by tehrenderr** [comment]
anything?

**Comment by tehrenderr** [comment]
bump :/

**Comment by tehrenderr** [comment]
@Europia79
