### ISSUE TITLE
PvP not being allowed

### ISSUE THREAD

**Issue by Fam-of3** [BattlePlugins/BattleArena#82]
We are running a smaller server and I'm having trouble getting a simple arena working according tto wiki. Even after searching the wiki for some insight on maybe an incorrect setting some place, like maybe pvp in the server.properties, worldguard config, or something needed to be set to 'pvp true'. 

We are running Spigot-1.10.2, 
WorldGuard 5.9.1-SNAPSHOT.1474-, 
PermissionsEx v1.22.7-SNAPSHOT, 
CoreProtect v2.12.0, 
Multiverse-Core Version: 2.5-b717, 
[BattleArena_v3.9.10.8,
Vault, as well this list
  PlayerHeads, AcceptRules, WorldEdit, TerrainControl, Essentials, EssentialsSpawn,
  EssentialsChat, BreakGlass, ZavAutoMessager, Votifier, SimpleSit,
  MyWarp, RegionSelfService, LWC, RewardVoting

  need anything from me just help me know what is needed and I'll find it.

  Am posting here cause IRC don't exist and email address return NULL

**Comment by Zach443** [comment]
IRC works just fine. We idle there 24/7. The page is just down that we used, go to http://webchat.esper.net and put #battleplugins as the channel name. It will be easier to troubleshoot there.

**Comment by Fam-of3** [comment]
Ah, kind of figured that was what happened to the website, anyways, I'll
pop on a bit later on and post for some help at the channel #battlearena.
Though do you have suggestion to possibly my error. Everything appears to
be working, just when another person and I tested to get an arena match
between us we didn't take any damage once match had started....  Thanks Fam

**Comment by Zach443** [comment]
#battlearena is not our channel. Use #battleplugins as I mentioned above.
