### ISSUE TITLE
none of pvp anticheats are working inside battlearena game

### ISSUE THREAD

**Issue by Govindass** [BattlePlugins/BattleArena#83]
I have noticed that my anticheat does not work on pvp cheats(like kill aura) which are used inside battlearena game, out of the game my anticheat blocks them fully and inside the game my anticheat has no effect on pvp hacks... Could you please fix this?(Not my anticheat problem, happens same thing with multiple anticheats!)

**Comment by Europia79** [comment]
What anti-cheat plugin are you using ?

Also, can you elaborate on exactly what cheats are being used ?

**Comment by Govindass** [comment]
From what I have found, cancelling player's damage with other plugins does not work.

I have tested with NoCheatPlus and my own made anticheat with skript, both does not cancel player's damage if they detect that player's hitting is similar to cheat.

Kill Aura - hits all players around you even if you aren't looking at them, so anticheat then tries to cancel player's damage if it detects that he is hitting like that, but inside battlearena game cancelling player's damage with any plugins does not work.

**Comment by Govindass** [comment]
Oh I found what was causing the problem! I removed all pvpOff and pvpOn options from my competition and it all works perfectly now! Sorry for saying that this is a bug.. Just my stupidity.

**Comment by Europia79** [comment]
No question is stupid btw. Thanks for posting the solution too !

You saved me from having to look thru the source code for what ```EntityDamageEvents``` are doing.

https://github.com/alkarinv/BattleArena/search?utf8=%E2%9C%93&q=EntityDamageEvent
