### ISSUE TITLE
FFA No Damage inside +

### ISSUE THREAD

**Issue by TKwSni** [BattlePlugins/BattleArena#84]
I'm getting this while inside a FFA arena

http://hastebin.com/raw/piwipukuza

I also get this everytime the server starts

http://hastebin.com/raw/elitukusud

BA version: 3.9.10.15
spigot 1.10.2

**Comment by RednedEpic** [comment]
I know it's been quite a while, but if you still somehow have the logs for this issue or can still replicate it. The links to the stacktraces you sent are expired.

**Comment by Blackyvk** [comment]
I dont even remember this issue sorry, I havent used this plugin since it was abandoned, but I might use it again if it has 1.13.2 compatibility
