### ISSUE TITLE
only 2 players?

### ISSUE THREAD

**Issue by Demonsbreathe** [BattlePlugins/BattleArena#85]
on my server, we created a few arenas and they were working fine, minimum of 2 players on each of them, max of "infinte" now its only allowing 2 players and it is crippling our servers PVP.

**Comment by Govindass** [comment]
I think you did something wrong in your game config, for me all works perfectly.

**Comment by Pigna** [comment]
Make sure your settings for that arena look somthing like:
gameSize:
      nTeams: 2+
      teamSize: 1+

In this example the minimum teams required are 2 and it can be more and the minimum teamsize is 1 but can be more.

**Comment by RednedEpic** [comment]
If you're still having trouble with this, please join us on Discord here https://discord.gg/tMVPVJf and we'll be happy to help you out. Most likely this is just a misconfiguration in your config file.

**Comment by Demonsbreathe** [comment]
Yo. This was 2 years ago.

**Comment by RednedEpic** [comment]
Yea, we've just recently picked up the plugin again and are actively updating it.

**Comment by Zach443** [comment]
@Demonsbreathe better late than never, amirite :D

**Comment by Demonsbreathe** [comment]
For sure. Just recently getting back into MC so maybe if it's being updated
again I'll take a peek back

**Comment by Zach443** [comment]
@Demonsbreathe Hop on the discord to keep up to date on the stuff we're doing 😃 

https://discord.gg/tMVPVJf
