### ISSUE TITLE
Wiki for BattleArena2 

### ISSUE THREAD

**Issue by Abyssmael** [BattlePlugins/BattleArena#86]
Hi There, 
We use BattleArena2 now nearly 6 month and learned a lot by trial & error. It's a really cool plugin an thanks a lot for this stuff. 
But now we wann to add spawning points for mobs & items, chamge the victoryconditions etc. I found only the old wiki on github from Alkarin_v and some of the old commands dont work. 
Where could i found an actually wiki for this awesome plugin? 
Greets

**Comment by Pigna** [comment]
Check out the Wiki button center top of the screen.

**Comment by Zach443** [comment]
Wiki is actually unavailable right now, I screwed up the DNS. I'll try to
get it fixed this weekend

**Comment by clovisd** [comment]
Hi there!

The wiki should be up and working at: https://wiki.battleplugins.org
