### ISSUE TITLE
Classes Not Found

### ISSUE THREAD

**Issue by StuckinTheMud01** [BattlePlugins/BattleArena#93]
Hi so this has happened lots. when i added the cmd to choose a kit to an npc, it'll work and be all fine but then randomly soon it'll stop and say 'class not found' Why?

This is my config file
version: 1.1

### You can add new classes here
classes:
    gladiator:
        displayName: "&4Gladiator" ### Used for signs
        items:
            - diamond_sword: sharp:1 1
            - bow: 1
            - arrow: 32
            - diamond_helm: 0
            - diamond_chest: 1
            - diamond_leggings: 1
            - diamond_boots: 1
            - 373;8229: 1 # potion of healing 2
            - 373;8193: 1 # potion of regen
            - 373;16396: 1 # splash potion of harming 1
        enchants:
            - speed:1:120
            - resistance:1:120
        doCommands:
            - console money take player 100
    archer:
        displayName: "&2Archer" ### Used for signs
        items:
            - iron_sword: sharp:1 1
            - bow: flame:2 power:3 punch:2 1
            - arrow: 32
            - leather_helm: 0
            - iron_chest: prot:3 1
            - leather_leggings: 1
            - leather_boots: 1
            - 373;8229: 1 # potion of healing 2
            - 373;8193: 1 # potion of regen
            - 373;16396: 1 # splash potion of harming 1
         doCommands:
            - console money take player 75
    monk:
        displayName: "&fMonk" ### Used for signs
        items:
            - leather_helm: 0
            - leather_chest: 1
            - leather_leggings: 1
            - leather_boots: 1
            - iron_sword: 1
            - 373;8229: 2 # potion of healing 2
            - 373;8193: 2 # potion of regen
            - 373;16396: 3 # splash potion of harming 1
        enchants:
            - strength:2:900 # increase attack power
            - speed:2:900 # increase movement
            - haste:2:900 # increase attack speed
            - resistance:1:900 # reduce damage taken
            - jump:2:900 # jump 2 blocks higher than normal
            - regen:1:60 # regen life
        doCommands:
            - console money take player 50

Thanks

**Comment by Europia79** [comment]
https://pastebin.com/

Go into your file & do Control+A & Control+C to select all & copy.

Paste it into Pastebin so I can see correct YAML formatting & line numbers.

Also, do a screenshot & paste of the log file (EOF).

**Comment by RednedEpic** [comment]
Unable to replicate. I don't think this is a problem with BattleArena, and if it is, most likely there is a mistake in your YML. If anyone else has this problem or this comes up again, please comment on this issue and I will gladly reopen it, or message us on Discord: https://discord.gg/tMVPVJf.
