### ISSUE TITLE
Lots of messages not translatable

### ISSUE THREAD

**Issue by Ferocimo** [BattlePlugins/BattleArena#99]
Hello,

There are quite a few messages that I couldn't translate on BattleArena. These are the ones I noticed so far : 
* Every message that has to do with "challenges" (/duel [player], etc), like "You challenged player to a dual", "player challenged you to a dual", "please type /duel accept or rescind" "Options:", "You have accepted the duel" ;
* The "Sill Alive" text in the scoreboard ;
* When you are in a queue for a dual and you leave, the "gamemode" for duals appears to be named "mydual". This can not be changed, apparently, and the message is something like "You left queue of myduel" ;
* Everything in the /arena help ;
* Everything you do with almost ANY command actually, since the messages.yml only allows translation of "announcements" (and by announcements I mean, what players see in their tchat depending on the situation at various stages of the matches). So every message displayed upon typing a command listed in /arena help is not translatable.

There are probably other things too, honestly it's quite difficult to scale on that scale, pretty much 70% of the "active" (= messages displayed when commands are typed) part of plugin is not translatable.

This is obviously a big issue for us since we litterally can't use your plugin on our server ; overall it works, but it wouldn't be understood by many of our young members (and also it would be quite unprofessionnal of us to set up a plugin half translated on our server).

Thank you for looking into this, I really look forward a fix.

**Comment by Ferocimo** [comment]
Just so I know, because I was working on this project, do you think this will be patched anytime soon ?

**Comment by RednedEpic** [comment]
I'm going to be working quite a bit with BattleArena in the next week or two for a custom gamemode I'm making. I have some local changes I need to push and get reviewed, but once those go through I'll look into this.

**Comment by Ferocimo** [comment]
I see, keep me posted then !

**Comment by Ferocimo** [comment]
@RednedEpic  So, do you think you'll be able to fix this anytime soon ?

**Comment by RednedEpic** [comment]
Hopefully soon, yea. It’s more of something that will be done over time rather than all done immediately considering how many messages we need to make translatable, as well as updating the old language files as well.

**Comment by Ferocimo** [comment]
@RednedEpic So, where are we with these changes ? It's been a year and a half ! :p

**Comment by clovisd** [comment]
This is possible with the new BA rewrite. Closing. :)
